### ISSUE TITLE
Environmental data does not load in clean database

### ISSUE THREAD

**Issue by dleehr** [NESCent/dplace#190]
Script that reads the CSV file fails to find the EnvironmentalVariable object matching the column name in the spreadsheet.
```
Warning: Did not find an EnvironmentalVariable with name Annual Mean Precipitation
Warning: Did not find an EnvironmentalVariable with name Slope
Warning: Did not find an EnvironmentalVariable with name Precipitation Contingency
Warning: Did not find an EnvironmentalVariable with name Temperature Contingency
Warning: Did not find an EnvironmentalVariable with name Bird Richness
Warning: Did not find an EnvironmentalVariable with name Amphibian Richness
Warning: Did not find an EnvironmentalVariable with name Precipitation Predictability
Warning: Did not find an EnvironmentalVariable with name Net Primary Production
Warning: Did not find an EnvironmentalVariable with name Vascular Plants Richness
Warning: Did not find an EnvironmentalVariable with name Mean Growing Season NPP
Warning: Did not find an EnvironmentalVariable with name Temperature Predictability
Warning: Did not find an EnvironmentalVariable with name Annual Temperature Variance
Warning: Did not find an EnvironmentalVariable with name Mammal Richness
Warning: Did not find an EnvironmentalVariable with name Inter-Year Variance Growing Season NPP
Warning: Did not find an EnvironmentalVariable with name Temperature Constancy
Warning: Did not find an EnvironmentalVariable with name Duration of Growing Season
```

**Comment by dleehr** [comment]
Appears issue is printing the data when loading the database:

```
$ python "${DPLACE_PATH}/dplace_app/load.py" datasets/csv/EcologicalData.DBASE.07Mar14.csv env_vars
Annual Precipitation Variance ()
Precipitation Constancy ()
Elevation ()
Annual Mean Temperature (°C)
Temperature Constancy ()
Duration of Growing Season (mo)
Annual Mean Precipitation (mm)
Slope ()
Precipitation Contingency ()
Temperature Contingency ()
Bird Richness ()
Amphibian Richness ()
Precipitation Predictability ()
Net Primary Production ()
Vascular Plants Richness ()
Mean Growing Season NPP ()
Temperature Predictability ()
Traceback (most recent call last):
  File "./dplace_app/load.py", line 75, in <module>
    run(sys.argv[1], sys.argv[2])
  File "./dplace_app/load.py", line 62, in run
    create_environmental_variables()
  File "/var/django/dplace/dplace_app/load/environmental.py", line 129, in create_environmental_variables
    print obj
  File "/home/dplace_user/env_dplace/local/lib/python2.7/site-packages/django/db/models/base.py", line 430, in __str__
    return force_text(self).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 29: ordinal not in range(128)
```
